### ISSUE TITLE
Create ways to message back and forth WITHOUT the android app

### ISSUE THREAD

**Issue by ZavenArra** [Greenstand/testing-tools#1]
Sync uploads from the android application use the following format, which also contains messages

https://greenstand.gitbook.io/mobile-app/upload-pack-format

We need a tool like what's found here to generate these packs:

https://github.com/Greenstand/testing-tools

**Comment by QuaidBartolomei** [comment]
@ZavenArra Does "message back and forth" mean that the testing script should expect a response?

**Comment by ZavenArra** [comment]
No need for the upload script to wait for a response.

A separate script can be created that accesses the API to get new messages for a given user.

**Comment by QuaidBartolomei** [comment]
Get the most recent message from the api, then generate and send a reply message

https://dev-k8s.treetracker.org/messaging/message?author_handle=handle1&since=2022-03-01T20:06:14
